# Class 2
January 25, 2018

In [1]:
my_string = "hello world"

In [2]:
print(my_string)

hello world


In [3]:
my_string[2]

'l'

## Slices 
Syntax of a slice: 'my_string[start:end]'<br>
'end' is not inclusive

In [12]:
my_string[0:5]

'hello'

To find the length of a string: len()

In [13]:
len(my_string)

11

In [16]:
my_string[0:len(my_string)-1] #or simply end index -1

'hello worl'

In [22]:
my_string[::-1]

'dlrow olleh'

### Exercise

In [33]:
banana = 'banana'

print(banana[1],banana[-1])

print(banana[1:4],banana[-3:])

a a
ana ana


## Slicing on NumPy Arrays
Arrays are the essential data structure in numerical computing. They are available to you via the numpy library. Load the library like this: 

In [34]:
import numpy as np

In [37]:
x = np.array([2, 4, 6, 8])

x[1:3]

array([4, 6])

In [41]:
y = np.linspace(0,100,26) #start,end,items (equal steps+1)

print(y)

[   0.    4.    8.   12.   16.   20.   24.   28.   32.   36.   40.   44.
   48.   52.   56.   60.   64.   68.   72.   76.   80.   84.   88.   92.
   96.  100.]


In [44]:
type(y)

numpy.ndarray

In [45]:
type(y[1])

numpy.float64

In [43]:
z = np.arange(0,100,4, dtype=float) #start, end, stepsize (end not included)
print(z)

[  0.   4.   8.  12.  16.  20.  24.  28.  32.  36.  40.  44.  48.  52.  56.
  60.  64.  68.  72.  76.  80.  84.  88.  92.  96.]


## 2 Dimensional Arrays

In [48]:
X = np.array([[1,2],[3,4]])

print(X)

[[1 2]
 [3 4]]


In [50]:
X[0,1] # second element first column

2

In [51]:
X[1,1] # second element in second column

4

In [52]:
X[0,:] # first row

array([1, 2])

In [53]:
X[:,0] # first column

array([1, 3])